#!/usr/bin/env python3
# -*- coding : utf-8 -*-
import logging
# logging.basicConfig(level=logging.INFO)

def application(environ,start_response):
    # logging.info(environ)
    start_response('200 OK',[('Content-Type','text/html')])
    body = '<h1>Hello,%s!</h1>' % (environ['PATH_INFO'][1:] or 'web')
    return [body.encode('utf-8')]

# {
#     'ALLUSERSPROFILE': 'C:\\ProgramData',
#     'APPDATA': 'C:\\Users\\XYY-001\\AppData\\Roaming',
#     'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
#     'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
#     'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
#     'COMPUTERNAME': 'DESKTOP-QU9JR6I',
#     'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
#     'DRIVERDATA': 'C:\\Windows\\System32\\Drivers\\DriverData',
#     'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
#     'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
#     'HOMEDRIVE': 'C:',
#     'HOMEPATH': '\\Users\\XYY-001',
#     'JAVA_HOME': 'D:\\Program Files\\java\\jre-8u211',
#     'LOCALAPPDATA': 'C:\\Users\\XYY-001\\AppData\\Local',
#     'LOGONSERVER': '\\\\DESKTOP-QU9JR6I',
#     'NUMBER_OF_PROCESSORS': '6',
#     'ONEDRIVE': 'C:\\Users\\XYY-001\\OneDrive',
#     'OS': 'Windows_NT',
#     'PATH': 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath;D:\\Program Files (x86)\\NetSarang\\Xshell 6\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;D:\\Program Files\\TortoiseSVN\\bin;C:\\ProgramData\\ComposerSetup\\bin;D:\\Program Files\\Git\\cmd;D:\\Program Files\\java\\jre-8u211\\bin;C:\\Program Files (x86)\\Calibre2\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;D:\\Program Files\\Python\\Scripts\\;D:\\Program Files\\Python\\;C:\\Users\\XYY-001\\AppData\\Local\\Microsoft\\WindowsApps;D:\\Program Files\\Microsoft VS Code\\bin;D:\\Install\\phpstudy_pro\\Extensions\\php\\php7.3.4nts;C:\\Users\\XYY-001\\AppData\\Roaming\\Composer\\vendor\\bin;D:\\Program Files (x86)\\Nmap;D:\\Program Files\\Bandizip\\;;D:\\Program Files\\fiddler;D:\\Program Files\\JetBrains\\PyCharm Community Edition 2019.3.3\\bin;',
#     'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL',
#     'PROCESSOR_ARCHITECTURE': 'AMD64',
#     'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 158 Stepping 10, GenuineIntel',
#     'PROCESSOR_LEVEL': '6',
#     'PROCESSOR_REVISION': '9e0a',
#     'PROGRAMDATA': 'C:\\ProgramData',
#     'PROGRAMFILES': 'C:\\Program Files',
#     'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
#     'PROGRAMW6432': 'C:\\Program Files',
#     'PSMODULEPATH': '......',
#     'PUBLIC': 'C:\\Users\\Public',
#     'PYCHARM COMMUNITY EDITION': '......;',
#     'SESSIONNAME': 'Console',
#     'SYSTEMDRIVE': 'C:',
#     'SYSTEMROOT': 'C:\\WINDOWS',
#     'TEMP': 'C:\\Users\\XYY-001\\AppData\\Local\\Temp',
#     'TMP': 'C:\\Users\\XYY-001\\AppData\\Local\\Temp',
#     'USERDOMAIN': 'DESKTOP-QU9JR6I',
#     'USERDOMAIN_ROAMINGPROFILE': 'DESKTOP-QU9JR6I',
#     'USERNAME': 'XYY-001',
#     'USERPROFILE': 'C:\\Users\\XYY-001',
#     'VBOX_MSI_INSTALL_PATH': 'D:\\Program Files\\Oracle\\VirtualBox\\',
#     'WINDIR': 'C:\\WINDOWS',
#     'MACTYPE_X64ADDR': '140723136357616',
#     'TERM_PROGRAM': 'vscode',
#     'TERM_PROGRAM_VERSION': '1.44.2',
#     'LANG': 'zh_CN.UTF-8',
#     'COLORTERM': 'truecolor',
#     'SERVER_NAME': 'DESKTOP-QU9JR6I',
#     'GATEWAY_INTERFACE': 'CGI/1.1',
#     'SERVER_PORT': '8000',
#     'REMOTE_HOST': '',
#     'CONTENT_LENGTH': '',
#     'SCRIPT_NAME': '',
#     'SERVER_PROTOCOL': 'HTTP/1.1',
#     'SERVER_SOFTWARE': 'WSGIServer/0.2',
#     'REQUEST_METHOD': 'GET',
#     'PATH_INFO': '/favicon.ico',
#     'QUERY_STRING': '',
#     'REMOTE_ADDR': '127.0.0.1',
#     'CONTENT_TYPE': 'text/plain',
#     'HTTP_HOST': 'localhost:8000',
#     'HTTP_CONNECTION': 'keep-alive',
#     'HTTP_PRAGMA': 'no-cache',
#     'HTTP_CACHE_CONTROL': 'no-cache',
#     'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36',
#     'HTTP_DNT': '1',
#     'HTTP_ACCEPT': 'image/webp,image/apng,image/*,*/*;q=0.8',
#     'HTTP_SEC_FETCH_SITE': 'same-origin',
#     'HTTP_SEC_FETCH_MODE': 'no-cors',
#     'HTTP_SEC_FETCH_DEST': 'empty',
#     'HTTP_REFERER': 'http://localhost:8000/',
#     'HTTP_ACCEPT_ENCODING': 'gzip,deflate,br',
#     'HTTP_ACCEPT_LANGUAGE': 'zh-CN,zh;q=0.9',
#     'HTTP_COOKIE': 'username-localhost-8888="2|1:0|10:1588144660|23:username-localhost-8888|44:NjlmYWMyMmYyNzliNDE3MGEwZDg4YTk4Nzk4MGJkMTY=|38d653058e88e87abbb8c0a06439d535d2c1a98931823a7fb970abc31a36e71a"; _xsrf=2|58ab3004|e4dd073ed009ba694711123b4744a6b7|1588144660; username-localhost-8889="2|1:0|10:1588144688|23:username-localhost-8889|44:M2UzZTNlODZkODBkNGEyMTlhM2JkZjRjYzljNzgxZDI=|4d4624d993fe17937967dc502ab065af1be64d86ecf4f243d9d78b09c9f67d48"',
#     'wsgi.input': <_io.BufferedReader name=756>,
#     'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
#     'wsgi.version': (1,0),
#     'wsgi.run_once': False,
#     'wsgi.url_scheme': 'http',
#     'wsgi.multithread': False,
#     'wsgi.multiprocess': False,
#     'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>
# }